# this file will facilitate the generation and searching of the wepages
# generated by WebCrawler.py

#take output from WebCralwer wich is a collection of text,

#multi-rake or open AI to extract key words

keywords = []

#now convert these